# fly.toml app configuration file generated for cocode-api-misty-waterfall-4489 on 2023-12-18T01:45:32-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cocode-api-misty-waterfall-4489"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
