spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://localhost/cocode_db
    username: root
    password: ${ROOT_KEY}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 1
  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    swagger-ui:
      path: /swagger-ui.html