INSERT INTO paises (codigo, nombre) VALUES('AR','Argentina');
INSERT INTO paises (codigo, nombre) VALUES('BZ','Belice');
INSERT INTO paises (codigo, nombre) VALUES('BO','Bolivia');
INSERT INTO paises (codigo, nombre) VALUES('BR','Brasil');
INSERT INTO paises (codigo, nombre) VALUES('CL','Chile');
INSERT INTO paises (codigo, nombre) VALUES('CO','Colombia');
INSERT INTO paises (codigo, nombre) VALUES('CR','Costa Rica');
INSERT INTO paises (codigo, nombre) VALUES('CU','Cuba');
INSERT INTO paises (codigo, nombre) VALUES('EC','Ecuador');
INSERT INTO paises (codigo, nombre) VALUES('SV','El Salvador');
INSERT INTO paises (codigo, nombre) VALUES('ES','España');
INSERT INTO paises (codigo, nombre) VALUES('GT','Guatemala');
INSERT INTO paises (codigo, nombre) VALUES('HO','Honduras');
INSERT INTO paises (codigo, nombre) VALUES('MX','México');
INSERT INTO paises (codigo, nombre) VALUES('NI','Nicaragua');
INSERT INTO paises (codigo, nombre) VALUES('PA','Panamá');
INSERT INTO paises (codigo, nombre) VALUES('PR','Puerto Rico');
INSERT INTO paises (codigo, nombre) VALUES('DO','República Dominicana');
INSERT INTO paises (codigo, nombre) VALUES('VE','Venezuela');

INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico1@mail.com', 'password', 1, 50, 1);
INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico2@mail.com', 'password', 2, 50, 1);
INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico3@mail.com', 'password', 3, 50, 0);
INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico4@mail.com', 'password', 4, 50, 1);
INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico5@mail.com', 'password', 5, 50, 0);
INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico6@mail.com', 'password', 6, 50, 1);
INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico7@mail.com', 'password', 7, 50, 1);
INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico8@mail.com', 'password', 8, 50, 1);
INSERT INTO usuarios (nombre, apellido, email, password, pais, puntos, activo) VALUES ('usuario', 'apellido', 'mailunico9@mail.com', 'password', 9, 50, 1);
