INSERT INTO paises (codigo_pais, nombre_pais) VALUES('AR','Argentina');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('BZ','Belice');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('BO','Bolivia');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('BR','Brasil');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('CL','Chile');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('CO','Colombia');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('CR','Costa Rica');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('CU','Cuba');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('EC','Ecuador');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('SV','El Salvador');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('ES','España');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('GT','Guatemala');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('HO','Honduras');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('MX','México');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('NI','Nicaragua');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('PA','Panamá');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('PR','Puerto Rico');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('DO','República Dominicana');
INSERT INTO paises (codigo_pais, nombre_pais) VALUES('VE','Venezuela');